name: custom_info_window
description: A widget based custom info window for google_maps_flutter package.
version: 0.0.4
repository: https://github.com/abhishekduhoon/custom_info_window
issue_tracker: https://github.com/abhishekduhoon/custom_info_window/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: